# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('msg', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(default='', max_length=120)),
                ('status', models.CharField(default='Pause', max_length=20)),
                ('token', models.CharField(max_length=420)),
                ('password_temp', models.CharField(blank=True, default='', max_length=420)),
                ('preferences', models.CharField(blank=True, default='', max_length=420)),
                ('avatar', models.ImageField(blank=True, default='profile-photos/default/musicify-icon.png', upload_to='media/profile-photos')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('length', models.IntegerField(default=0)),
                ('album', models.CharField(max_length=200)),
                ('cover', models.ImageField(blank=True, default='album-artworks/default/musicify-icon.png', upload_to='media/album-artworks')),
                ('artist', models.CharField(max_length=200)),
                ('preview', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='disliked',
            field=models.ManyToManyField(blank=True, related_name='disliked', to='meradio.Song'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to='meradio.Song'),
        ),
        migrations.AddField(
            model_name='profile',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_song', to='meradio.Song'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='current_song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meradio.Song'),
        ),
        migrations.AddField(
            model_name='chat',
            name='host',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='listeners',
            field=models.ManyToManyField(blank=True, related_name='listeners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(blank=True, to='meradio.Message'),
        ),
    ]
