# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meradio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pause_duration',
            field=models.FloatField(default=b'0'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(default=b'Stopped', max_length=20),
        ),
    ]
